require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstituteMembersController do

  # This should return the minimal set of attributes required to create a valid
  # InstituteMember. As you add validations to InstituteMember, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all institute_members as @institute_members" do
      institute_member = InstituteMember.create! valid_attributes
      get :index
      assigns(:institute_members).should eq([institute_member])
    end
  end

  describe "GET show" do
    it "assigns the requested institute_member as @institute_member" do
      institute_member = InstituteMember.create! valid_attributes
      get :show, :id => institute_member.id.to_s
      assigns(:institute_member).should eq(institute_member)
    end
  end

  describe "GET new" do
    it "assigns a new institute_member as @institute_member" do
      get :new
      assigns(:institute_member).should be_a_new(InstituteMember)
    end
  end

  describe "GET edit" do
    it "assigns the requested institute_member as @institute_member" do
      institute_member = InstituteMember.create! valid_attributes
      get :edit, :id => institute_member.id.to_s
      assigns(:institute_member).should eq(institute_member)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstituteMember" do
        expect {
          post :create, :institute_member => valid_attributes
        }.to change(InstituteMember, :count).by(1)
      end

      it "assigns a newly created institute_member as @institute_member" do
        post :create, :institute_member => valid_attributes
        assigns(:institute_member).should be_a(InstituteMember)
        assigns(:institute_member).should be_persisted
      end

      it "redirects to the created institute_member" do
        post :create, :institute_member => valid_attributes
        response.should redirect_to(InstituteMember.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved institute_member as @institute_member" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstituteMember.any_instance.stub(:save).and_return(false)
        post :create, :institute_member => {}
        assigns(:institute_member).should be_a_new(InstituteMember)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstituteMember.any_instance.stub(:save).and_return(false)
        post :create, :institute_member => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested institute_member" do
        institute_member = InstituteMember.create! valid_attributes
        # Assuming there are no other institute_members in the database, this
        # specifies that the InstituteMember created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstituteMember.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => institute_member.id, :institute_member => {'these' => 'params'}
      end

      it "assigns the requested institute_member as @institute_member" do
        institute_member = InstituteMember.create! valid_attributes
        put :update, :id => institute_member.id, :institute_member => valid_attributes
        assigns(:institute_member).should eq(institute_member)
      end

      it "redirects to the institute_member" do
        institute_member = InstituteMember.create! valid_attributes
        put :update, :id => institute_member.id, :institute_member => valid_attributes
        response.should redirect_to(institute_member)
      end
    end

    describe "with invalid params" do
      it "assigns the institute_member as @institute_member" do
        institute_member = InstituteMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstituteMember.any_instance.stub(:save).and_return(false)
        put :update, :id => institute_member.id.to_s, :institute_member => {}
        assigns(:institute_member).should eq(institute_member)
      end

      it "re-renders the 'edit' template" do
        institute_member = InstituteMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstituteMember.any_instance.stub(:save).and_return(false)
        put :update, :id => institute_member.id.to_s, :institute_member => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested institute_member" do
      institute_member = InstituteMember.create! valid_attributes
      expect {
        delete :destroy, :id => institute_member.id.to_s
      }.to change(InstituteMember, :count).by(-1)
    end

    it "redirects to the institute_members list" do
      institute_member = InstituteMember.create! valid_attributes
      delete :destroy, :id => institute_member.id.to_s
      response.should redirect_to(institute_members_url)
    end
  end

end
