require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UploadedfilesController do

  # This should return the minimal set of attributes required to create a valid
  # Uploadedfile. As you add validations to Uploadedfile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all uploadedfiles as @uploadedfiles" do
      uploadedfile = Uploadedfile.create! valid_attributes
      get :index
      assigns(:uploadedfiles).should eq([uploadedfile])
    end
  end

  describe "GET show" do
    it "assigns the requested uploadedfile as @uploadedfile" do
      uploadedfile = Uploadedfile.create! valid_attributes
      get :show, :id => uploadedfile.id.to_s
      assigns(:uploadedfile).should eq(uploadedfile)
    end
  end

  describe "GET new" do
    it "assigns a new uploadedfile as @uploadedfile" do
      get :new
      assigns(:uploadedfile).should be_a_new(Uploadedfile)
    end
  end

  describe "GET edit" do
    it "assigns the requested uploadedfile as @uploadedfile" do
      uploadedfile = Uploadedfile.create! valid_attributes
      get :edit, :id => uploadedfile.id.to_s
      assigns(:uploadedfile).should eq(uploadedfile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Uploadedfile" do
        expect {
          post :create, :uploadedfile => valid_attributes
        }.to change(Uploadedfile, :count).by(1)
      end

      it "assigns a newly created uploadedfile as @uploadedfile" do
        post :create, :uploadedfile => valid_attributes
        assigns(:uploadedfile).should be_a(Uploadedfile)
        assigns(:uploadedfile).should be_persisted
      end

      it "redirects to the created uploadedfile" do
        post :create, :uploadedfile => valid_attributes
        response.should redirect_to(Uploadedfile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved uploadedfile as @uploadedfile" do
        # Trigger the behavior that occurs when invalid params are submitted
        Uploadedfile.any_instance.stub(:save).and_return(false)
        post :create, :uploadedfile => {}
        assigns(:uploadedfile).should be_a_new(Uploadedfile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Uploadedfile.any_instance.stub(:save).and_return(false)
        post :create, :uploadedfile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested uploadedfile" do
        uploadedfile = Uploadedfile.create! valid_attributes
        # Assuming there are no other uploadedfiles in the database, this
        # specifies that the Uploadedfile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Uploadedfile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => uploadedfile.id, :uploadedfile => {'these' => 'params'}
      end

      it "assigns the requested uploadedfile as @uploadedfile" do
        uploadedfile = Uploadedfile.create! valid_attributes
        put :update, :id => uploadedfile.id, :uploadedfile => valid_attributes
        assigns(:uploadedfile).should eq(uploadedfile)
      end

      it "redirects to the uploadedfile" do
        uploadedfile = Uploadedfile.create! valid_attributes
        put :update, :id => uploadedfile.id, :uploadedfile => valid_attributes
        response.should redirect_to(uploadedfile)
      end
    end

    describe "with invalid params" do
      it "assigns the uploadedfile as @uploadedfile" do
        uploadedfile = Uploadedfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Uploadedfile.any_instance.stub(:save).and_return(false)
        put :update, :id => uploadedfile.id.to_s, :uploadedfile => {}
        assigns(:uploadedfile).should eq(uploadedfile)
      end

      it "re-renders the 'edit' template" do
        uploadedfile = Uploadedfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Uploadedfile.any_instance.stub(:save).and_return(false)
        put :update, :id => uploadedfile.id.to_s, :uploadedfile => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested uploadedfile" do
      uploadedfile = Uploadedfile.create! valid_attributes
      expect {
        delete :destroy, :id => uploadedfile.id.to_s
      }.to change(Uploadedfile, :count).by(-1)
    end

    it "redirects to the uploadedfiles list" do
      uploadedfile = Uploadedfile.create! valid_attributes
      delete :destroy, :id => uploadedfile.id.to_s
      response.should redirect_to(uploadedfiles_url)
    end
  end

end
